/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PendingLoans.java
 *
 * Created on Apr 25, 2012, 1:33:15 PM
 */
package com.loansystem.UI.employee;

import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Antonve
 */
public class PendingLoansRequestsTab extends javax.swing.JPanel {

    /** Creates new form PendingLoans */
     public PendingLoansRequestsTab(ArrayList<JPanel> pendingLoansPanels) {
        initComponents();
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS) );
        //JPanel testPanel = new NewLoanRequestPanel();
        //add(testPanel);
        for(JPanel panel : pendingLoansPanels) 
        {
            add(panel);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    // End of variables declaration
}
