/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PendingLoansPanel.java
 *
 * Created on Apr 25, 2012, 2:53:32 PM
 */
package com.loansystem.UI.employee;

import com.loansystem.backend.model.PendingLoansTabModel;

import com.loansystem.model.Client;
import com.loansystem.model.Loan;
import com.loansystem.model.User;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Antonve
 */
public class PendingLoansPanel extends javax.swing.JPanel {

    /** Creates new form PendingLoansPanel */
    private boolean visibility;
    private PendingLoansTabModel pendingLoansTabModel;
    //private ArrayList<Loan> loansList;

    public PendingLoansPanel(PendingLoansTabModel pendingLoansTabModel, boolean b) {
        initComponents();

        ArrayList<Loan> loansList = pendingLoansTabModel.getPendingLoans();
        //newLoanRequestTable.put(NewLoanRequestConstants.COL_1, Loan.class.getDeclaredField(TOOL_TIP_TEXT_KEY));
        Loan currentLoan;
        int i = 0;
        Object[][] tableObject = new Object[loansList.size()][6];

        PendingLoansTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


        Iterator loanRequests = loansList.iterator();
        while (loanRequests.hasNext()) {




            currentLoan = (Loan) loanRequests.next();
            User user = pendingLoansTabModel.getUser();
            Client client = user.getClients().get(0);


            tableObject[i][0] = currentLoan.getLoanId();

            tableObject[i][1] = user.getName() + " " + user.getLastName();

            //tableObject[i][1] = currentLoan.getLoanHistory().get(0).getDate();
            if (currentLoan.getLoanHistory().size() > 0) {
                tableObject[i][2] = currentLoan.getLoanHistory().get(0).getDate();
            } else {
                tableObject[i][2] = "";
            }
            tableObject[i][3] = currentLoan.getLoanOffer().getSum();
            tableObject[i][4] = client.getRating();
            tableObject[i][5] = client.getClientGroup().getDescription();

            i++;
        }
        PendingLoansTable.setModel(new javax.swing.table.DefaultTableModel(
                tableObject,
                new String[]{
                    "Loan id", "Client", "Date requested", "Sum", "Client rating", "Client group"
                }));
        this.setVisible(b);
        //session.close();
    }

    public PendingLoansTabModel getPendingLoansTabModel() {
        return pendingLoansTabModel;
    }

    public void setPendingLoansTabModel(PendingLoansTabModel pendingLoansTabModel) {
        this.pendingLoansTabModel = pendingLoansTabModel;
    }

    public boolean isVisibility() {
        return visibility;
    }

    public void setVisibility(boolean visibility) {
        this.visibility = visibility;
    }

    public PendingLoansPanel() {
    }

    public JTable getPendingLoansTable() {
        return PendingLoansTable;
    }

    public void setPendingLoansTable(JTable PendingLoansTable) {
        this.PendingLoansTable = PendingLoansTable;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PendingLoansTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(552, 150));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        PendingLoansTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Loan id", "Client", "Date requeted", "Sum", "Client rating", "Client group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PendingLoansTable.setAlignmentY(0.0F);
        PendingLoansTable.setAutoscrolls(false);
        PendingLoansTable.setName("PendingLoansTable"); // NOI18N
        jScrollPane1.setViewportView(PendingLoansTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("PendingLoansPanel"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PendingLoansTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public Loan getSelectedLoan(int row) {
        int columns = PendingLoansTable.getColumnCount();
        // String s = "Are you sure your choice is the loan with next parameters: \n";
        Loan selectedLoanRequest = new Loan();
        selectedLoanRequest.setLoanId((Integer) PendingLoansTable.getValueAt(row, 0));

        return selectedLoanRequest;
    }
}
