/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PendingLoanControlsPanel.java
 *
 * Created on Apr 25, 2012, 4:31:07 PM
 */
package com.loansystem.UI.employee;

import com.loansystem.backend.model.LoanTabModel;
import com.loansystem.backend.model.PendingLoansTabModel;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author Antonve
 */
public class PendingLoanControlsPanel extends javax.swing.JPanel {
    
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private LoanTabModel loanTabModel;

    /** Creates new form PendingLoanControlsPanel */
    public PendingLoanControlsPanel() {
        initComponents();
    }

    public PendingLoanControlsPanel(PendingLoansTabModel pendingLoansTabModel, boolean b) {
        this.loanTabModel = loanTabModel;
        initComponents();
        setBorder(BorderFactory.createTitledBorder("Pending Loan Controls"));
        
        initComponents(this.loanTabModel);
        setVisible(b);
    }

    private void initComponents(LoanTabModel loanTabModel) {


        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        //jButton3 = new javax.swing.JButton();

        jButton1.setText("Accept Loan Request");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVisible(false);
        
        jButton2 = new javax.swing.JButton();
        jButton2.setText("Reject Loan Request");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVisible(false);



       /* jButton3.setText("Postpone payback");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVisible(false);*/

        /*jButton4.setText("Cancel Postpone payback request");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVisible(false);*/

        GridLayout layout = new GridLayout(2, 1);


        setLayout(layout);

        add(jButton1, 0);
        add(jButton2, 1);
        //add(jButton3, 2);
        //add(jButton4, 3);
        
        setButtonsVisibility(false);
        

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    private void setButtonsVisibility(boolean b) {
       jButton1.setVisible(b);
       jButton1.setVisible(b);
    }
}
