package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * CientGroup generated by hbm2java
 */
public class CientGroup implements java.io.Serializable {

    private String id;
    private String name;
    private String description;
    private List<Client> clients;
    private List<LoanOffer> loanOffers;

    public List<LoanOffer> getLoanOffers() {
        return loanOffers;
    }

    public void setLoanOffers(List<LoanOffer> loanOffers) {
        this.loanOffers = loanOffers;
    }

    public CientGroup() {
    }

    public CientGroup(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public CientGroup(String id, String name, String description, List<Client> clients, List<LoanOffer> loanOffers) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.clients = clients;
        this.loanOffers = loanOffers;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Client> getClients() {
        return this.clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }
}
