package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * ClientGroup generated by hbm2java
 */
public class ClientGroup implements java.io.Serializable {

    private String groupId;
    private String name;
    private String description;
    private int minRating;
    private int maxRating;
    private List<Client> clients;

    public int getMaxRating() {
        return maxRating;
    }

    public void setMaxRating(int maxRating) {
        this.maxRating = maxRating;
    }

    public int getMinRating() {
        return minRating;
    }

    public void setMinRating(int minRating) {
        this.minRating = minRating;
    }

   
    private List<LoanOffer> loanOffers;

    public List<LoanOffer> getLoanOffers() {
        return loanOffers;
    }

    public void setLoanOffers(List<LoanOffer> loanOffers) {
        this.loanOffers = loanOffers;
    }

    public ClientGroup() {
    }

    public ClientGroup(String groupId, String name) {
        this.groupId = groupId;
        this.name = name;
    }

    public ClientGroup(String groupId, String name, String description, int minRating, int maxRating, List<Client> clients, List<LoanOffer> loanOffers) {
        this.groupId = groupId;
        this.name = name;
        this.description = description;
        this.minRating = minRating;
        this.maxRating = maxRating;
        this.clients = clients;
        this.loanOffers = loanOffers;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Client> getClients() {
        return this.clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }
}
