package com.loansystem.model;

// default package
import java.util.List;
import java.util.Set;

// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

    private int clientId;
    private ClientGroup ClientGroup;
    private ClientStatus clientStatus;
    private String rating;
    private List<Loan> loans;
    private User user;
    private List<ClientHistory> clientHistory;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Client() {
    }

    public Client(int clientId, ClientGroup ClientGroup, ClientStatus clientStatus, int persCode, String rating, List<Loan> loans, User user, List<ClientHistory> clientHistory) {
        this.clientId = clientId;
        this.ClientGroup = ClientGroup;
        this.clientStatus = clientStatus;
        this.user = user;
        this.rating = rating;
        this.loans = loans;
        this.clientHistory = clientHistory;
    }

    public int getClientId() {
        return this.clientId;
    }

    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    public ClientGroup getClientGroup() {
        return this.ClientGroup;
    }

    public void setClientGroup(ClientGroup ClientGroup) {
        this.ClientGroup = ClientGroup;
    }

    public ClientStatus getClientStatus() {
        return this.clientStatus;
    }

    public void setClientStatus(ClientStatus clientStatus) {
        this.clientStatus = clientStatus;
    }

    public String getRating() {
        return this.rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public List<Loan> getLoans() {
        return loans;
    }

    public List<ClientHistory> getClientHistory() {
        return clientHistory;
    }

    public void setClientHistory(List<ClientHistory> clientHistory) {
        this.clientHistory = clientHistory;
    }

    public void setLoans(List<Loan> loans) {
        this.loans = loans;
    }
}
