package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
/**
 * ClientHistory generated by hbm2java
 */
public class ClientHistory implements java.io.Serializable {

    private int id;
    private String date;
    private String comment;
    private Client client;
    private ClientGroup clientGroup;
    private ClientStatus clientStatus;
    private double newRating;
    
    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public double getNewRating() {
        return newRating;
    }

    public void setNewRating(double newRating) {
        this.newRating = newRating;
    }

    public ClientGroup getClientGroup() {
        return clientGroup;
    }

    public void setClientGroup(ClientGroup clientGroup) {
        this.clientGroup = clientGroup;
    }

    public ClientStatus getClientStatus() {
        return clientStatus;
    }

    public void setClientStatus(ClientStatus clientStatus) {
        this.clientStatus = clientStatus;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    public ClientHistory() {
        
    }

    public ClientHistory(int id,
            String date,
            String comment,
            Client client,
            ClientGroup clientGroup,
            ClientStatus clientStatus,
            double newRating) {
        this.id = id;
        this.date = date;
        this.comment = comment;
        this.client = client;
        this.clientGroup = clientGroup;
        this.clientStatus = clientStatus;
        this.newRating = newRating;
    }

   
}
