package com.loansystem.model;

// default package
import java.util.List;
import java.util.Set;

// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

    private int clientId;
    private CientGroup cientGroup;
    private ClientStatus clientStatus;
    private int persCode;
    private String rating;
    private List<Loan> loans;

    public Client() {
    }

    public Client(int clientId, CientGroup cientGroup, ClientStatus clientStatus, int persCode, String rating, List<Loan> loans) {
        this.clientId = clientId;
        this.cientGroup = cientGroup;
        this.clientStatus = clientStatus;
        this.persCode = persCode;

        this.rating = rating;
        this.loans = loans;
    }

    public int getClientId() {
        return this.clientId;
    }

    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    public CientGroup getCientGroup() {
        return this.cientGroup;
    }

    public void setCientGroup(CientGroup cientGroup) {
        this.cientGroup = cientGroup;
    }

    public ClientStatus getClientStatus() {
        return this.clientStatus;
    }

    public void setClientStatus(ClientStatus clientStatus) {
        this.clientStatus = clientStatus;
    }

    public int getPersCode() {
        return persCode;
    }

    public void setPersCode(int persCode) {
        this.persCode = persCode;
    }

    public String getRating() {
        return this.rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public List<Loan> getLoans() {
        return loans;
    }

    public void setLoans(List<Loan> loans) {
        this.loans = loans;
    }
}
