package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private String emloyeeId;
	private int persCode;
	private int employeeType;

	public Employee() {
	}

	public Employee(int persCode, String name, int employeeType) {
		this.emloyeeId = emloyeeId;
		this.persCode = persCode;
		this.employeeType = employeeType;
	}

	
	public int getPersCode() {
		return this.persCode;
	}

	public void setPersCode(int persCode) {
		this.persCode = persCode;
	}

    public String getEmloyeeId() {
        return emloyeeId;
    }

    public void setEmloyeeId(String emloyeeId) {
        this.emloyeeId = emloyeeId;
    }

    public int getEmployeeType() {
        return employeeType;
    }

    public void setEmployeeType(int employeeType) {
        this.employeeType = employeeType;
    }

	
}
