package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoanStatus generated by hbm2java
 */
public class LoanStatus implements java.io.Serializable {

	private String loanStatusId;
	private String name;
	private String description;

	public LoanStatus() {
	}

	public LoanStatus(String id, String name) {
		this.loanStatusId = id;
		this.name = name;
	}

	public LoanStatus(String id, String name, String description) {
		this.loanStatusId = id;
		this.name = name;
		this.description = description;
	}

	public String getLoanStatusId() {
		return this.loanStatusId;
	}

	public void setLoanStatusId(String id) {
		this.loanStatusId = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
