package com.loansystem.model;

// default package

import java.util.HashSet;
import java.util.Set;




// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Loan generated by hbm2java
 */
public class Loan implements java.io.Serializable {

	private int loanId;
	private String dueDate;
	private String baseDueDate;
	private String apr;
	private String debt;
	private Client client;
	private String employeeId;
	private String offerId;
	private String postponeRequestId;
        private Set<LoanStatus> loanStatusSet;

	public Loan() {
	}

	public Loan(int id, String dueDate, String baseDueDate, String apr, String debt, int clientId, Set<LoanStatus> loanStatusSet,
			String offerId) {
		this.loanId = id;
		this.dueDate = dueDate;
		this.baseDueDate = baseDueDate;
		this.apr = apr;
		this.debt = debt;
		this.client = client;
		this.loanStatusSet = loanStatusSet;
		this.offerId = offerId;
	}

	public Loan(int id, String dueDate, String baseDueDate, String apr, String debt, int clientId,
			String employeeId, Set<LoanStatus> loanStatusSet, String offerId, String postponeRequestId) {
		this.loanId = id;
		this.dueDate = dueDate;
		this.baseDueDate = baseDueDate;
		this.apr = apr;
		this.debt = debt;
		this.client = client;
		this.employeeId = employeeId;
		this.loanStatusSet = loanStatusSet;
		this.offerId = offerId;
		this.postponeRequestId = postponeRequestId;
	}

	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int id) {
		this.loanId = id;
	}

	public String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(String dueDate) {
		this.dueDate = dueDate;
	}

	public String getBaseDueDate() {
		return this.baseDueDate;
	}

	public void setBaseDueDate(String baseDueDate) {
		this.baseDueDate = baseDueDate;
	}

	public String getApr() {
		return this.apr;
	}

	public void setApr(String apr) {
		this.apr = apr;
	}

	public String getDebt() {
		return this.debt;
	}

	public void setDebt(String debt) {
		this.debt = debt;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public Set<LoanStatus> getLoanStatusSet() {
		return this.loanStatusSet;
	}

	public void setLoanStatusSet(Set<LoanStatus> loanStatusSet) {
		this.loanStatusSet = loanStatusSet;
	}

	public String getOfferId() {
		return this.offerId;
	}

	public void setOfferId(String offerId) {
		this.offerId = offerId;
	}

	public String getPostponeRequestId() {
		return this.postponeRequestId;
	}

	public void setPostponeRequestId(String postponeRequestId) {
		this.postponeRequestId = postponeRequestId;
	}

}
