package com.loansystem.model;

// default package
import java.util.Date;

// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1
/**
 * LoanHistory generated by hbm2java
 */
public class LoanHistory implements java.io.Serializable {

    private int rowId;
    private String event;
    private String date; //Date decide sql or java
    private Loan loan;

    public void setDate(String date) {
        this.date = date;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    public Loan getLoan() {
        return loan;
    }

    public void setLoan(Loan loan) {
        this.loan = loan;
    }

    public String getDate() {
        return date;
    }

    public String getEvent() {
        return event;
    }

    public int getRowId() {
        return rowId;
    }
}
