package com.loansystem.model;

// default package
// Generated Feb 18, 2012 4:26:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int persCode;
	private int id;
	private String name;
	private String lastName;
	private String mail;
	private String password;

	public User() {
	}

	public User(int persCode) {
		this.persCode = persCode;
	}

	public User(int persCode, Integer id, String name, String lastName, String mail, String password) {
		this.persCode = persCode;
		this.id = id;
		this.name = name;
		this.lastName = lastName;
		this.mail = mail;
		this.password = password;
	}

	public int getPersCode() {
		return this.persCode;
	}

	public void setPersCode(int persCode) {
		this.persCode = persCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
