package com.loansystem.model;

// default package
// Generated Feb 18, 2012 4:26:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

	private int id;
	private String persCode;
	private String isClient;
	private String isEmployee;
	private Integer employeeType;

	public UserDetail() {
	}

	public UserDetail(int id) {
		this.id = id;
	}

	public UserDetail(int id, String persCode, String isClient, String isEmployee, Integer employeeType) {
		this.id = id;
		this.persCode = persCode;
		this.isClient = isClient;
		this.isEmployee = isEmployee;
		this.employeeType = employeeType;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPersCode() {
		return this.persCode;
	}

	public void setPersCode(String persCode) {
		this.persCode = persCode;
	}

	public String getIsClient() {
		return this.isClient;
	}

	public void setIsClient(String isClient) {
		this.isClient = isClient;
	}

	public String getIsEmployee() {
		return this.isEmployee;
	}

	public void setIsEmployee(String isEmployee) {
		this.isEmployee = isEmployee;
	}

	public Integer getEmployeeType() {
		return this.employeeType;
	}

	public void setEmployeeType(Integer employeeType) {
		this.employeeType = employeeType;
	}

}
