package com.loansystem.model;

// default package
// Generated Feb 18, 2012 4:26:51 PM by Hibernate Tools 3.4.0.CR1
/**
 * UserDetail generated by hbm2java
 */
public class UserDetail implements java.io.Serializable {

    private int userDetailId;
    private int persCode;
    private String isClient;
    private String isEmployee;
    private int employeeType;
    private Client client;
    private Employee employee;

    public UserDetail() {
    }

    public UserDetail(int id) {
        this.userDetailId = id;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public UserDetail(int userDetailId, int persCode, String isClient, String isEmployee, int employeeType, Client client, Employee employee ) {
        this.userDetailId = userDetailId;
        this.persCode = persCode;
        this.isClient = isClient;
        this.isEmployee = isEmployee;
        this.employeeType = employeeType;
        this.client = client;
        this.employee = employee;

    }

    public int getUserDetailId() {
        return this.userDetailId;
    }

    public int getEmployeeType() {
        return employeeType;
    }

    public void setEmployeeType(int employeeType) {
        this.employeeType = employeeType;
    }

    public void setUserDetailId(int userDetailId) {
        this.userDetailId = userDetailId;
    }

    public int getPersCode() {
        return this.persCode;
    }

    public void setPersCode(int persCode) {
        this.persCode = persCode;
    }

    public String getIsClient() {
        return this.isClient;
    }

    public void setIsClient(String isClient) {
        this.isClient = isClient;
    }

    public String getIsEmployee() {
        return this.isEmployee;
    }

    public void setIsEmployee(String isEmployee) {
        this.isEmployee = isEmployee;
    }

    public void setEmployeeType(Integer employeeType) {
        this.employeeType = employeeType;
    }
}
