/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExistingLoanRequestControls.java
 *
 * Created on Feb 5, 2012, 2:36:22 PM
 */
package com.loansystem.UI.client;

import java.awt.event.ActionListener;
import javax.swing.BorderFactory;

/**
 *
 * @author antonve
 */
public class ExistingLoanRequestControls extends javax.swing.JPanel {

    /** Creates new form ExistingLoanRequestControls */
    public ExistingLoanRequestControls() {
        initComponents();
        setBorder(BorderFactory.createTitledBorder("Exisiting Loan Controls"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("Pay Back");
        jButton2.setName("jButton2"); // NOI18N

        jButton1.setText("Remove Loan Request");
        jButton1.setName("jButton1"); // NOI18N

        jButton3.setText("Postpone payback");
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
    public void addRejectListener(ActionListener mal) {
        jButton1.addActionListener(mal);
    }

    public void addPayBackListener(ActionListener payBackListener) {
        jButton2.addActionListener(payBackListener);
    }

    public void addPostponeListener(ActionListener postponeListener) {
        jButton3.addActionListener(postponeListener);
    }
}
