/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewLoanRequestTabJPanel.java
 *
 * Created on 03.12.2011, 13:08:06
 */
package com.loansystem.UI.client;

import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Andrey Andrievski
 */
public class LoanRequestCTab extends javax.swing.JPanel {

    /** Creates new form AddNewLoanRequestTabJPanel */
    public LoanRequestCTab(JPanel[] panels) {
        initComponents();
        setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS) );
        //JPanel testPanel = new NewLoanRequestPanel();
        //add(testPanel);
        for(JPanel panel : panels) 
        {
            add(panel);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("AddNewLoanRequestTabJPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
