/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewLoanRequestPanel.java
 *
 * Created on Dec 11, 2011, 4:42:28 PM
 */
package com.loansystem.UI.client;

import com.loansystem.model.LoanOffer;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.ListSelectionModel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author antonve
 */
public class NewLoanRequestPanel extends javax.swing.JPanel {
    
     private static final Log log = LogFactory.getLog(NewLoanRequestPanel.class);

    /** Creates new form NewLoanRequestPanel */
    public NewLoanRequestPanel(List<LoanOffer> loanOffersList) {
        initComponents();
        LoanOffer currentLoanOffer;
        int i = 0;
        Object[][] tableObject = new Object[loanOffersList.size()][4];
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


        Iterator loanOfferSet = loanOffersList.iterator();
        while (loanOfferSet.hasNext()) {

            currentLoanOffer = (LoanOffer) loanOfferSet.next();
            tableObject[i][0] = currentLoanOffer.getSum();          
            tableObject[i][1] = currentLoanOffer.getPeriod();
            tableObject[i][2] = currentLoanOffer.getRatingBonus();
            tableObject[i][3] = currentLoanOffer.getApr();
            
            i++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableObject,
                new String[]{
                    "SUM", "DAYS", "RATING+", "APR"
                }));

    }

    public NewLoanRequestPanel() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
     private void displayRowValues(int rowIndex)  
    {  
        int columns = jTable1.getColumnCount();  
        String s = "";  
        for(int col = 0; col < columns; col++)  
        {  
            Object o = jTable1.getValueAt(rowIndex, col);  
            s += o.toString();  
            if(col < columns - 1)  
                s += ", ";  
                log.info(s);
        }  
        //readRow.label.setText(s);  
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Available Loan Offers");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("Request a loan");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Create loan Request
        
      int rowIndex = jTable1.getSelectedRow();
      
      displayRowValues(rowIndex);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
