/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PostponeRequestPanel.java
 *
 * Created on Feb 5, 2012, 12:06:05 AM
 */
package com.loansystem.UI.client;

import com.loansystem.backend.model.LoanTabModel;
import com.loansystem.control.FrameBuilderImpl;
import com.loansystem.model.Client;
import com.loansystem.model.Loan;
import com.loansystem.model.LoanOffer;
import com.loansystem.util.DateUtil;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.Date;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author antonve
 */
public class PostponeRequestPanel extends javax.swing.JPanel {

    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private JButton jButton2;

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider2;
    private static final Log log = LogFactory.getLog(FrameBuilderImpl.class);
    private final int MIN_DAYS = 0;
    private final LoanTabModel loanTabModel;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;

    /** Creates new form PostponeRequestPanel */
    public PostponeRequestPanel(boolean visibility, LoanTabModel loanTabModel) {

        this.loanTabModel = loanTabModel;

        Loan lastLoan = loanTabModel.getLastLoan();

        // jSlider1 = new JSlider(JSlider.HORIZONTAL, minDays, maxDays, middleDays);

        // jSlider1.addChangeListener(new SliderStateChangedListener());

        //Loan Offer.Sum * (1 + Loan Offer.APR* Loan Offer.periodDays/(100 * 365)
        LoanOffer loanOffer = lastLoan.getLoanOffer();

        int[] sliderOpts = new int[3];
        sliderOpts[0] = MIN_DAYS;
        sliderOpts[1] = Integer.parseInt(loanOffer.getPeriod()) / 4;
        sliderOpts[2] = Integer.parseInt(loanOffer.getPeriod()) / 2;


        float initialSum = Float.parseFloat(lastLoan.getDebt());
        float apr = Float.parseFloat(loanOffer.getApr());
        int days = Integer.parseInt(loanOffer.getPeriod());
        String initialDueDate = lastLoan.getDueDate();

        int fps = sliderOpts[1];
        log.info("Current Days Selected: " + fps);

        //String oldDueDate = lastLoan.getDueDate();
        Date oldDate;
        try {
            oldDate = DateUtil.dateFormat.parse(initialDueDate);
            Date newDueDate = DateUtil.getDatePlusDays(oldDate, fps);
            String dueDateString = DateUtil.dateFormat.format(newDueDate);
            log.info("Current Due  Date : " + newDueDate);
            int debt = Math.round(initialSum * (1 + apr * (fps + days) / (100 * 365)));
            float newSum = debt;
            log.info("Current sum : " + newSum);

            String dueDateAsString = String.valueOf(dueDateString);
            String dueSumAsString = String.valueOf(newSum);

            initComponents(sliderOpts, dueDateAsString, dueSumAsString);
        } catch (ParseException ex) {
            Logger.getLogger(PostponeRequestPanel.class.getName()).log(Level.SEVERE, null, ex);
        }




        //Loan Offer.Sum * (1 + Loan Offer.APR* Loan Offer.periodDays/(100 * 365)


        /*
        Hashtable labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel(String.valueOf(minDays)));
        labelTable.put(new Integer(middleDays), new JLabel(String.valueOf(middleDays)));
        labelTable.put(new Integer(maxDays), new JLabel(String.valueOf(maxDays)));
        jSlider1.setLabelTable(labelTable);*/


        this.setVisible(visibility);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(int[] sliderOpts, String dueDateAsString, String sumAsString) {


        jSlider1 = new JSlider(JSlider.HORIZONTAL, sliderOpts[0], sliderOpts[2], sliderOpts[1]);

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setName("jSlider1"); // NOI18N

        setBorder(BorderFactory.createTitledBorder("Postpone Request Controls"));


        // jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        //jSlider1.setName("jSlider1"); // NOI18N

        jLabel1.setText("Due Date: ");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Sum : ");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(dueDateAsString);
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(sumAsString);
        jLabel4.setName("jLabel4"); // NOI18N

        jButton1.setText("Create Postpone request");
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setText("Cancel");
        jButton2.setName("jButton2"); // NOI18N



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel4)).addGroup(layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel3)).addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(layout.createSequentialGroup().addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jButton2))).addContainerGap(56, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(31, 31, 31).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jLabel3)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(jLabel4)).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton1).addComponent(jButton2)).addContainerGap(30, Short.MAX_VALUE)));
    }// </editor-fold>

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JSlider getjSlider1() {
        return jSlider1;
    }

    public void setjSlider1(JSlider jSlider1) {
        this.jSlider1 = jSlider1;
    }

    public void addSliderListener(ChangeListener sliderStateChangedListener) {
        jSlider1.addChangeListener(sliderStateChangedListener);
    }

    public void addPostponeConfirmListener(ActionListener postponeConfirmListener) {
        jButton1.addActionListener(postponeConfirmListener);
    }

    public void addPostponeCancelListener(ActionListener loanPostponeCancelListener) {
        jButton2.addActionListener(loanPostponeCancelListener);
    }
}// </editor-fold>
// Variables declaration - do not modify
/*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();

        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel3)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
 */
